//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_CNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hóa_đơn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hóa_đơn()
        {
            this.Chi_tiết_hóa_đơn = new HashSet<Chi_tiết_hóa_đơn>();
        }
    
        public string ID { get; set; }
        public string ID_NV { get; set; }
        public System.DateTime Ngày_bán { get; set; }
        public int Tổng_SL { get; set; }
        public int Tổng_tiền { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chi_tiết_hóa_đơn> Chi_tiết_hóa_đơn { get; set; }
        public virtual Nhân_viên Nhân_viên { get; set; }
    }
}
