//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_CNPM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class taphoa_finalEntities2 : DbContext
    {
        public taphoa_finalEntities2()
            : base("name=taphoa_finalEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Chi_tiết_hóa_đơn> Chi_tiết_hóa_đơn { get; set; }
        public virtual DbSet<ChucNang> ChucNang { get; set; }
        public virtual DbSet<ĐVT> ĐVT { get; set; }
        public virtual DbSet<Hàng_Hóa> Hàng_Hóa { get; set; }
        public virtual DbSet<Hóa_đơn> Hóa_đơn { get; set; }
        public virtual DbSet<Loại> Loại { get; set; }
        public virtual DbSet<Nhân_viên> Nhân_viên { get; set; }
        public virtual DbSet<PhanQuyen> PhanQuyen { get; set; }
    }
}
